@startuml

abstract class Plant{
   int flag
   long createTime;
   long closeTime
   long belangsId
   float  importantRatio
   int colorStart
   int colorEnd
   String[] targets
   String name
   String[] steps
   String reason
   String[] disturbances//干扰因素
   int PlantStatus//
   int FinishStatus//
   int finishMark
   int  summaryId
   int  PlantStatus
}


SeasonPlan  <|-- Plant
MonthPlan  <|-- Plant
WeekPlan  <|-- Plant



@enduml