package com.example.greendaolib.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.greendaolib.pojo.db.GroupString;
import com.example.greendaolib.pojo.db.PlanStatus;
import com.example.greendaolib.pojo.db.PlanSummary;
import com.example.greendaolib.pojo.db.Plant;

import com.example.greendaolib.dao.GroupStringDao;
import com.example.greendaolib.dao.PlanStatusDao;
import com.example.greendaolib.dao.PlanSummaryDao;
import com.example.greendaolib.dao.PlantDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig groupStringDaoConfig;
    private final DaoConfig planStatusDaoConfig;
    private final DaoConfig planSummaryDaoConfig;
    private final DaoConfig plantDaoConfig;

    private final GroupStringDao groupStringDao;
    private final PlanStatusDao planStatusDao;
    private final PlanSummaryDao planSummaryDao;
    private final PlantDao plantDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        groupStringDaoConfig = daoConfigMap.get(GroupStringDao.class).clone();
        groupStringDaoConfig.initIdentityScope(type);

        planStatusDaoConfig = daoConfigMap.get(PlanStatusDao.class).clone();
        planStatusDaoConfig.initIdentityScope(type);

        planSummaryDaoConfig = daoConfigMap.get(PlanSummaryDao.class).clone();
        planSummaryDaoConfig.initIdentityScope(type);

        plantDaoConfig = daoConfigMap.get(PlantDao.class).clone();
        plantDaoConfig.initIdentityScope(type);

        groupStringDao = new GroupStringDao(groupStringDaoConfig, this);
        planStatusDao = new PlanStatusDao(planStatusDaoConfig, this);
        planSummaryDao = new PlanSummaryDao(planSummaryDaoConfig, this);
        plantDao = new PlantDao(plantDaoConfig, this);

        registerDao(GroupString.class, groupStringDao);
        registerDao(PlanStatus.class, planStatusDao);
        registerDao(PlanSummary.class, planSummaryDao);
        registerDao(Plant.class, plantDao);
    }
    
    public void clear() {
        groupStringDaoConfig.getIdentityScope().clear();
        planStatusDaoConfig.getIdentityScope().clear();
        planSummaryDaoConfig.getIdentityScope().clear();
        plantDaoConfig.getIdentityScope().clear();
    }

    public GroupStringDao getGroupStringDao() {
        return groupStringDao;
    }

    public PlanStatusDao getPlanStatusDao() {
        return planStatusDao;
    }

    public PlanSummaryDao getPlanSummaryDao() {
        return planSummaryDao;
    }

    public PlantDao getPlantDao() {
        return plantDao;
    }

}
